## Conda environment for https://github.com/dkirkby/kavli2019

name: K19
channels:
  - anaconda
  - conda-forge   # needed for jupyterlab, jupyter_contrib_nbextensions, emcee
  - pytorch       # needed for pytorch-cpu, torchvision-cpu
dependencies:
  - python=3.7
  - pip           # ensures that any pip installs only modify this env
  - ipython
  - jupyter
  - jupyterlab    # needed for "jupyter lab"
  - ipykernel     # ensures that (base) nb_conda creates a kernel for this env
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - hdf5
  - pytables
  - pillow
  - libiconv       # needed by jupyter_contrib_nbextensions on some platforms
  - jupyter_contrib_nbextensions
  - emcee
  - pytorch-cpu
  - torchvision-cpu
  - pip:
    - pyro-ppl       # pytorch probabilistic programming
    - fastai         # pytorch best practices library
